### ISSUE TITLE
Adding a text timed out: Livy

### ISSUE THREAD

**Issue by bilbe** [Hedera-Lang-Learn/hedera#35] opened 2019-03-21 13:54 UTC
Livy, Ab Urbe Condita
https://hederaproject.org/lemmatized_text/1/

When I added the intro to Livy's Ab Urbe Condita, it timed out. Here are some facts/red herrings:
- it was the first text in our environment to be added
- the text is 316 words long with an extra return between paragraphs

The second time I tried it was added properly:
- I had removed extra returns between paragraphs, this may or may not have helped

Wonder if enough of the lemma lattice was built by the time I tried the second time and so it was faster. And it was noticeably faster.

**Comment by jtauber** [comment] 2019-03-21 15:08
The issue is mostly we haven't pre-loaded any big hash of form-to-lemma mappings so every single word is a call to Morpheus.

There are three things we should do:

1. pre-load form-to-lemma mappings from Helma Dik
2. background the lemmatisation task as a job so it's not done in the request/response cycle of the browser
3. batch calls to Morpheus (it can take multiple words in a call but we're not making use of that)

**Comment by jtauber** [comment] 2019-04-04 17:48
Patrick has implemented 2 which solves the problem. 1 & 3 would just speed things up.

**Comment by bilbe** [comment] 2019-07-18 18:45
Here's the error message I get from the background process when things fail:

```
18:41:37 default: lemmatized_text.models.lemmatize_text_job('ASTRONOMICUS NUNCIUS OBSERVATIONES RECENS HABITAS Novi Perspicilli beneficio in lunae facie, Lacteo circulo Stellisque nebulosis, innumeris fixis, necnon in quatuor Planetis MEDICEA SIDERA nuncupatis, numquam conspectis adhuc continens, atque declarans. Magna equidem in hac exigua tractatione singulis de natura speculantibus inspicienda contemplandaque propono. Magna, inquam, tum ob rei ipsius præstantiam, tum ob inauditam per ævum novitatem, tum etiam propter Organum, cuius beneficio eadem sensui nostro obviam sese fecerunt. Magnum sane est, supra numerosam inerrantium Stellarum multitudinem, quæ naturali facultate in hunc usque diem conspici potuerunt, alias innumeras superaddere oculisque palam exponere, antehac conspectas nunquam, et quæ veteres ac notas plusquam supra decuplam multiplicitatem superent. Pulcherrimum atque visu iucundissimum est, lunare corpus, per sex denas fere terrestres semidiametros a nobis remotum, tam ex propinquo intueri, ac si per', 'lat', 16) (0ea666a0-2e5d-4231-8886-56c872aba865)
18:41:37 Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 11)
```

**Comment by IvyJL** [comment] 2020-07-31 18:57
I think this is fixed as of 2020-07-31. I added an 800+ word text with extra returns.

**Closed by IvyJL** 2020-07-31 18:57 UTC
